console.log('[LLB] service worker started');

import type { DetectionResult } from '../shared/types';

chrome.runtime.onInstalled.addListener(() => {
  console.log('[LLB] extension installed');
  chrome.action.setBadgeBackgroundColor({ color: '#0077B5' });
});

// ---------------------------------------------------------------------------
// Storage-driven badge — counts pending flagged accounts (D-09, D-10, D-11)
// Badge reflects live queue size; decrements automatically on dismiss.
// ---------------------------------------------------------------------------

chrome.storage.onChanged.addListener((changes, area) => {
  if (area !== 'local' || !changes['flaggedAccounts']) return;
  const accounts = (changes['flaggedAccounts'].newValue ?? {}) as Record<string, { status: string }>;
  const pendingCount = Object.values(accounts).filter(a => a.status === 'pending').length;
  chrome.action.setBadgeText({ text: pendingCount > 0 ? String(pendingCount) : '' });
  chrome.action.setBadgeBackgroundColor({ color: '#0077B5' });
});

const SYSTEM_PROMPT = `You are an AI content detector for LinkedIn posts. Analyze the post and determine if it was generated by an AI writing tool.

Return ONLY a JSON object — no markdown, no extra text:
{
  "score": <integer 0-100>,
  "signals": { "<signal-name>": <integer contribution> },
  "reasoning": "<one sentence>"
}

Score guide:
- 0–34: Likely human-written
- 35–59: Possibly AI-generated — flag for review
- 60–100: Likely AI-generated — will be hidden from feed

Signal names to use (only include those that apply):
- "hook-story": Fictional anecdote opener ("A senior engineer at Google discovered...")
- "listicle-cta": Numbered list structure + engagement closer
- "buzzword": Overuse of business buzzwords (leverage, synergy, game-changer, disruption)
- "em-dash": Heavy em-dash use — like this — in short punchy clauses
- "ai-vocab": AI-characteristic words (delve, meticulous, tapestry, fostering, pivotal, navigate, realm)
- "motivational": Short punchy paragraphs building to an inspirational conclusion
- "generic-cta": "What do you think?", "Let's connect!", "DM me", "Which one are you?", "Agree?"
- "template": Obvious problem → solution → CTA template structure

Signal contribution values should sum approximately to the score.`;

async function scorePost(postText: string): Promise<DetectionResult> {
  const result = await chrome.storage.local.get(['anthropicApiKey']);
  const apiKey = result.anthropicApiKey as string | undefined;
  if (!apiKey) throw new Error('No API key configured');

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 400,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: postText }],
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`API ${response.status}: ${body}`);
  }

  const data = await response.json() as { content: Array<{ text: string }> };
  const raw = data.content[0]?.text ?? '';
  const jsonStr = raw.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim();
  const parsed = JSON.parse(jsonStr) as { score: number; signals: Record<string, number> };

  const score = Math.min(100, Math.max(0, Math.round(parsed.score)));
  const breakdown: Record<string, number> = parsed.signals ?? {};

  return {
    score,
    signals: Object.keys(breakdown),
    signalBreakdown: breakdown,
    confidence: score >= 60 ? 'high' : score >= 35 ? 'medium' : 'low',
    engineUsed: 'llm',
  };
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message?.type === 'POST_HIDDEN') {
    // Badge is now updated via chrome.storage.onChanged on flaggedAccounts — see above
    return false;
  }

  if (message?.type === 'SCORE_POST') {
    scorePost(message.postText as string)
      .then(result => sendResponse({ result }))
      .catch(err => sendResponse({ error: (err as Error).message }));
    return true; // keep channel open for async response
  }

  return false;
});
